---
book_repo: pivotal-cf/docs-book-partners
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

# products:

sections:

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-a9s-bosh
    at_path: docs-content
  directory: partners/a9s-bosh
  subnav_template: a9s-bosh_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-consul
    at_path: docs-content
  directory: partners/a9s-consul-dns
  subnav_template: a9s-consul-dns_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-elasticsearch
    at_path: docs-content
  directory: partners/a9s-elasticsearch
  subnav_template: a9s-elasticsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-mongodb
    at_path: docs-content
  directory: partners/a9s-mongodb
  subnav_template: a9s-mongodb_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-postgresql
    at_path: docs-content
  directory: partners/a9s-postgresql
  subnav_template: a9s-postgresql.erb
- repository:
    name: pivotal-cf/docs-a9s-rabbitmq
    at_path: docs-content
  directory: partners/a9s-rabbitmq
  subnav_template: a9s-rabbitmq_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-redis
    at_path: docs-content
  directory: partners/a9s-redis
  subnav_template: a9s-redis_subnav.erb
- repository:
    name: pivotal-cf/docs-aerospike
    at_path: docs-content
  directory: partners/aerospike
  subnav_template: aerospike_subnav.erb
- repository:
    name: pivotal-cf/docs-aerospike-ee
    at_path: docs-content
  directory: partners/aerospike-ee-managed-service
  subnav_template: aerospike_ee_subnav.erb
- repository:
    name: pivotal-cf/docs-aerospike-ondemand
    at_path: docs-content
  directory: partners/aerospike-ondemand
  subnav_template: aerospike-ondemand_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-aws-s3
    at_path: docs-content
  directory: partners/altoros-aws-s3
  subnav_template: altoros-aws-s3_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-cassandra
    at_path: docs-content
  directory: partners/altoros-cassandra
  subnav_template: altoros-cassandra_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-elasticsearch
    at_path: docs-content
  directory: partners/altoros-elasticsearch
  subnav_template: altoros-elasticsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-heartbeat
    at_path: docs-content
  directory: partners/altoros-heartbeat
  subnav_template: altoros-heartbeat_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-jenkins
    at_path: docs-content
  directory: partners/altoros-jenkins
  subnav_template: altoros-jenkins_subnav.erb
- repository:
    name: pivotal-cf/docs-altoros-logsearch
    at_path: docs-content
  directory: partners/altoros-logsearch
  subnav_template: altoros-logsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-apigee
  directory: partners/apigee
  subnav_template: apigee_subnav.erb
- repository:
    name: pivotal-cf/docs-apigee-bosh
    at_path: docs-content
  directory: partners/edge-installer
  subnav_template: apigee_bosh_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics
  directory: partners/appdynamics
  subnav_template: _appdynamics_subnav.erb
- repository:
    name: pivotal-cf/docs-azuqua
  directory: partners/azuqua
  subnav_template: azuqua_subnav.erb
- repository:
    name: pivotal-cf/docs-azure
    at_path: docs-content
  directory: partners/azure-sb
  subnav_template: azuresb_subnav.erb
- repository:
    name: pivotal-cf/docs-azure-analytics
    at_path: docs-content
  directory: partners/azure-log-analytics-nozzle
  subnav_template: azure-log-analytics-nozzle_subnav.erb
- repository:
    name: pivotal-cf/docs-blackduck
    at_path: docs-content
  directory: partners/blackduck-service-broker
  subnav_template: blackduck-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-blue-medora
    at_path: docs-content
  directory: partners/blue-medora
  subnav_template: blue_medora_subnav.erb
- repository:
    name: pivotal-cf/docs-boomi-atomsphere-int-services
    at_path: docs-content
  directory: partners/boomi-atomsphere-int-services
  subnav_template: boomi-atomsphere-int-services_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees
  directory: partners/cloudbees
  subnav_template: pivotal_cloudbees_service_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudflare
    at_path: docs-content
  directory: partners/cloudflare-service-broker
  subnav_template: cloudflare_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudsoft
  directory: partners/cloudsoft
  subnav_template: cloudsoft_subnav.erb
- repository:
    name: pivotal-cf/docs-contrast-service-broker
    at_path: docs-content
  directory: partners/contrast-service-broker
  subnav_template: contrast-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-crunchy-data
    at_path: docs-content
  directory: partners/crunchy
  subnav_template: crunchy_subnav.erb
- repository:
    name: pivotal-cf/docs-datastax
    at_path: docs-content
  directory: partners/datastax-service-broker
  subnav_template: datastax-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-datastax-enterprise
    at_path: docs-content
  directory: partners/datastax-enterprise
  subnav_template: datastax-enterprise_subnav.erb
- repository:
    name: pivotal-cf/docs-dyadic-service-broker
    at_path: docs-content
  directory: partners/dyadic-service-broker
  subnav_template: dyadic-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-dynatrace
    at_path: docs-content
  directory: partners/dynatrace
  subnav_template: pivotal_dynatrace_service_subnav.erb
- repository:
    name: pivotal-cf/docs-dynatrace-fullstack-addon
    at_path: docs-content
  directory: partners/dynatrace-fullstack-addon
  subnav_template: dynatrace-fullstack-addon_subnav.erb
- repository:
    name: pivotal-cf/docs-ecs-service-broker
  directory: partners/ecs-service-broker
  subnav_template: ecs-service-broker_subnav.erb.erb
- repository:
    name: pivotal-cf/docs-edb-postgres
  directory: partners/edb-postgres
  subnav_template: pivotal_edb_postgres.erb
- repository:
    name: pivotal-cf/docs-edb-postgres-ark-sb
    at_path: docs-content
  directory: partners/edb-postgres-ark-sb
  subnav_template: edb-postgres-ark-sb_subnav.erb
- repository:
    name: pivotal-cf/docs-erlang-wombat
    at_path: docs-content
  directory: partners/wombat
  subnav_template: erlang_wombat_subnav.erb
- repository:
    name: pivotal-cf/docs-firstdata
    at_path: docs-content
  directory: partners/firstdata
  subnav_template: firstdata_subnav.erb
- repository:
    name: pivotal-cf/docs-forgerock
    at_path: docs-content
  directory: partners/forgerock
  subnav_template: forgerock_subnav.erb
- repository:
    name: pivotal-cf/docs-gcp-stackdriver
    at_path: docs-content
  directory: partners/gcp-sdn
  subnav_template: GCP-Stackdriver_subnav.erb
- repository:
    name: pivotal-cf/docs-gitlab
  directory: partners/gitlab
  subnav_template: pivotal_gitlab_service_subnav.erb
- repository:
    name: pivotal-cf/docs-gluon-cloudlink
    at_path: docs-content
  directory: partners/gluon-cloudlink
  subnav_template: gluon-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-google
    at_path: docs-content
  directory: partners/gcp-sb
  subnav_template: gcpsb_subnav.erb
- repository:
    name: pivotal-cf/docs-guardtime
  directory: partners/guardtime
  subnav_template: pivotal_guardtime.erb
- repository:
    name: pivotal-cf/docs-hazelcast
    at_path: docs-content
  directory: partners/hazelcast
  subnav_template: hazelcast_subnav.erb
- repository:
    name: pivotal-cf/docs-hazelcast-jet
    at_path: docs-content
  directory: partners/hazelcast-jet
  subnav_template: hazelcast-jet_subnav.erb
- repository:
    name: pivotal-cf/docs-honeycomb
    at_path: docs-content
  directory: partners/honeycomb-nozzle
  subnav_template: honeycomb_subnav.erb
- repository:
    name: pivotal-cf/docs-jfrog
  directory: partners/jfrog
  subnav_template: pivotal_jfrog_service_subnav.erb
- repository:
    name: pivotal-cf/docs-klacloud
  directory: partners/knowtify
  subnav_template: pivotal_knowtify_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mongodb-managed
    at_path: docs-content
  directory: partners/mongodb
  subnav_template: pivotal_mongodb_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mulesoft-anypoint
    at_path: docs-content
  directory: partners/mulesoft
  subnav_template: mulesoft_subnav.erb
- repository:
    name: pivotal-cf/docs-neo4j
  directory: partners/neo4j
  subnav_template: pivotal_neo4j_service_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic
  directory: partners/newrelic
  subnav_template: pivotal_new_relic_service_subnav.erb
- repository:
    name: pivotal-cf/docs-pagerduty-service-broker
    at_path: docs-content
  directory: partners/pagerduty
  subnav_template: pagerduty-service-broker_subnav.erb
- repository:
    name: pivotal-cf/docs-pega
    at_path: docs-content
  directory: partners/pega
  subnav_template: pega_subnav.erb
- repository:
    name: pivotal-cf/docs-redislabs-enterprise
    at_path: docs-content
  directory: partners/redis-labs-enterprise-pack
  subnav_template: redis-labs-enterprise_subnav.erb
- repository:
    name: pivotal-cf/docs-rle-service-broker
  directory: partners/rle-service-broker
  subnav_template: pivotal_rle_service_broker.erb
- repository:
    name: pivotal-cf/docs-signalfx
    at_path: docs-content
  directory: partners/signalfx
  subnav_template: signalfx_subnav.erb
- repository:
    name: pivotal-cf/docs-signal-sciences
    at_path: docs-content
  directory: partners/signalsciences
  subnav_template: signalsciences_subnav.erb
- repository:
    name: pivotal-cf/docs-solace-messaging
    at_path: docs-content
  directory: partners/solace-messaging
  subnav_template: pivotal_solace_messaging.erb
- repository:
    name: pivotal-cf/docs-splunk
    at_path: docs-content
  directory: partners/splunk
  subnav_template: splunk_subnav.erb
- repository:
    name: pivotal-cf/docs-stardog
    at_path: docs-content
  directory: partners/stardog-service-broker
  subnav_template: stardog_subnav.erb
- repository:
    name: pivotal-cf/docs-sumologic
    at_path: docs-content
  directory: partners/sumologic-nozzle
  subnav_template: sumologic_subnav.erb
- repository:
    name: pivotal-cf/docs-sw-shield
    at_path: docs-content
  directory: partners/starkandwayne-shield
  subnav_template: starkandwayne_shield_subnav.erb
- repository:
    name: pivotal-cf/docs-tibco-businessworks
  directory: partners/tibco-businessworks
  subnav_template: tibco_businessworks_subnav.erb
- repository:
    name: pivotal-cf/docs-wavefront-nozzle
    at_path: docs-content
  directory: partners/wavefront-nozzle
  subnav_template: wavefront-nozzle_subnav.erb
- repository:
    name: dingotiles/dingo-docs
    at_path: docs-dingo-postgresql
  directory: partners/dingo-postgresql
  subnav_template: _dingo_postgresql_subnav.erb
