---
book_repo: pivotal-cf/docs-book-partners
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

# products:

sections:

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-a9s-bosh
    at_path: docs-content
  directory: a9s-bosh
  subnav_template: a9s-bosh_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-consul
    at_path: docs-content
  directory: a9s-consul-dns
  subnav_template: a9s-consul-dns_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-elasticsearch
    at_path: docs-content
  directory: a9s-elasticsearch
  subnav_template: a9s-elasticsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-mongodb
    at_path: docs-content
  directory: a9s-mongodb
  subnav_template: a9s-mongodb_subnav.erb
- repository:
    name: pivotal-cf/docs-a9s-postgresql
    at_path: docs-content
  directory: a9s-postgresql
  subnav_template: a9s-postgresql.erb
- repository:
    name: pivotal-cf/docs-aerospike
    at_path: docs-content
  directory: aerospike
  subnav_template: aerospike_subnav.erb
- repository:
    name: pivotal-cf/docs-aerospike-ee
    at_path: docs-content
  directory: aerospike-ee
  subnav_template: aerospike_ee_subnav.erb
- repository:
    name: pivotal-cf/docs-apigee
  directory: apigee
  subnav_template: apigee_subnav.erb
- repository:
    name: pivotal-cf/docs-apigee-bosh
    at_path: docs-content
  directory: apigee-bosh
  subnav_template: apigee_bosh_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics
  directory: appdynamics
  subnav_template: _appdynamics_subnav.erb
- repository:
    name: pivotal-cf/docs-azuqua
  directory: azuqua
  subnav_template: azuqua_subnav.erb
- repository:
    name: pivotal-cf/docs-azure
    at_path: docs-content
  directory: azure-sb
  subnav_template: azuresb_subnav.erb
- repository:
    name: pivotal-cf/docs-blue-medora
    at_path: docs-content
  directory: blue-medora
  subnav_template: blue_medora_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees
  directory: cloudbees
  subnav_template: pivotal_cloudbees_service_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudsoft
  directory: cloudsoft
  subnav_template: cloudsoft_subnav.erb
- repository:
    name: pivotal-cf/docs-crunchy-data
    at_path: docs-content
  directory: crunchy
  subnav_template: crunchy_subnav.erb
- repository:
    name: pivotal-cf/docs-dynatrace
    at_path: docs-content
  directory: dynatrace
  subnav_template: pivotal_dynatrace_service_subnav.erb
- repository:
    name: pivotal-cf/docs-edb-postgres
  directory: edb-postgres
  subnav_template: pivotal_edb_postgres.erb
- repository:
    name: pivotal-cf/docs-erlang-wombat
    at_path: docs-content
  directory: wombat
  subnav_template: erlang_wombat_subnav.erb
- repository:
    name: pivotal-cf/docs-firstdata
    at_path: docs-content
  directory: firstdata
  subnav_template: firstdata_subnav.erb
- repository:
    name: pivotal-cf/docs-forgerock
    at_path: docs-content
  directory: forgerock
  subnav_template: forgerock_subnav.erb
- repository:
    name: pivotal-cf/docs-gitlab
  directory: gitlab
  subnav_template: pivotal_gitlab_service_subnav.erb
- repository:
    name: pivotal-cf/docs-google
    at_path: docs-content
  directory: gcp-sb
  subnav_template: gcpsb_subnav.erb
- repository:
    name: pivotal-cf/docs-guardtime
  directory: guardtime
  subnav_template: pivotal_guardtime.erb
- repository:
    name: pivotal-cf/docs-hazelcast
    at_path: docs-content
  directory: hazelcast
  subnav_template: hazelcast_subnav.erb
- repository:
    name: pivotal-cf/docs-jfrog
  directory: jfrog
  subnav_template: pivotal_jfrog_service_subnav.erb
- repository:
    name: pivotal-cf/docs-klacloud
  directory: knowtify
  subnav_template: pivotal_knowtify_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mongodb-managed
    at_path: docs-content
  directory: mongodb
  subnav_template: pivotal_mongodb_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mulesoft-anypoint
    at_path: docs-content
  directory: mulesoft
  subnav_template: mulesoft_subnav.erb
- repository:
    name: pivotal-cf/docs-neo4j
  directory: neo4j
  subnav_template: pivotal_neo4j_service_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic
  directory: newrelic
  subnav_template: pivotal_new_relic_service_subnav.erb
- repository:
    name: pivotal-cf/docs-rlec
  directory: rlec
  subnav_template: pivotal_rlec.erb
- repository:
    name: pivotal-cf/docs-signal-sciences
    at_path: docs-content
  directory: signalsciences
  subnav_template: signalsciences_subnav.erb
- repository:
    name: pivotal-cf/docs-solace-messaging
    at_path: docs-content
  directory: solace-messaging
  subnav_template: pivotal_solace_messaging.erb
- repository:
    name: pivotal-cf/docs-splunk
    at_path: docs-content
  directory: splunk
  subnav_template: splunk_subnav.erb
- repository:
    name: pivotal-cf/docs-tibco-businessworks
  directory: tibco-businessworks
  subnav_template: tibco_businessworks_subnav.erb
- repository:
    name: dingotiles/dingo-docs
    at_path: docs-dingo-postgresql
  directory: dingo-postgresql
  subnav_template: _dingo_postgresql_subnav.erb
